sudo: required
language: generic
services:
  - docker
before_install:
  - GIT_REVISION=`git rev-parse HEAD`
  - echo "Building revision $GIT_REVISION"
  - echo $GIT_REVISION > rev.txt
  # Decrypt the Gcloud service account file
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Download and install the Google cloud SDK
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Configure the SDK with our Gcloud auth info
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-289420
  - gcloud config set compute/zone us-west1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t tarof429/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tarof429/react-test npm test

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master